# Generated by Django 5.2.8 on 2025-11-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_runtime', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttasklog',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='agents.agent'),
        ),
        migrations.AddIndex(
            model_name='agenttasklog',
            index=models.Index(fields=['agent', '-created_at'], name='agent_runti_agent_i_e5506d_idx'),
        ),
    ]
