# Generated by Django 5.2.8 on 2025-11-29 06:14

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username_display', models.CharField(blank=True, help_text='A public username for the user.', max_length=150, null=True, unique=True, verbose_name='Display Username')),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('institutional', 'Institutional'), ('developer', 'Developer')], default='individual', max_length=20, verbose_name='User Type')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Email Verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Is Account Locked')),
                ('is_demo', models.BooleanField(default=True, verbose_name='Is Demo Account')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Account Locked Until')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Login At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Last Name')),
                ('display_name', models.CharField(blank=True, max_length=128, verbose_name='Display Name')),
                ('phone_number', models.CharField(blank=True, max_length=32, verbose_name='Phone Number')),
                ('nationality', models.CharField(blank=True, max_length=64, verbose_name='Nationality')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Two-Factor Authentication Enabled')),
                ('api_access_enabled', models.BooleanField(default=False, verbose_name='API Access Enabled')),
                ('max_api_requests_per_minute', models.IntegerField(default=1000, verbose_name='Max API Requests Per Minute')),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma separated list of IPs allowed to access the API.', verbose_name='Allowed IPs')),
                ('preferred_base_currency', models.CharField(default='IRT', max_length=16, verbose_name='Preferred Base Currency')),
                ('default_leverage', models.IntegerField(default=1, verbose_name='Default Leverage')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=20, verbose_name='Risk Level')),
                ('max_active_trades', models.IntegerField(default=5, verbose_name='Max Active Trades')),
                ('max_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Maximum Allowed Capital (Demo/Real)')),
                ('notify_on_trade', models.BooleanField(default=True, verbose_name='Notify on Trade Execution')),
                ('notify_on_balance_change', models.BooleanField(default=True, verbose_name='Notify on Balance Change')),
                ('notify_on_risk_limit_breach', models.BooleanField(default=True, verbose_name='Notify on Risk Limit Breach')),
                ('is_kyc_verified', models.BooleanField(default=False, verbose_name='Is KYC Verified')),
                ('kyc_document_type', models.CharField(blank=True, max_length=32, verbose_name='KYC Document Type')),
                ('kyc_document_number', models.CharField(blank=True, max_length=64, verbose_name='KYC Document Number')),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='KYC Submitted At')),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='KYC Verified At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
