# Generated by Django 5.2.8 on 2025-11-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_demo',
            field=models.BooleanField(default=True, verbose_name='Is Demo Account'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login At'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Account Locked Until'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_ips',
            field=models.TextField(blank=True, help_text='Comma separated list of IPs allowed to access the API.', verbose_name='Allowed IPs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_kyc_verified',
            field=models.BooleanField(default=False, verbose_name='Is KYC Verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_document_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='KYC Document Number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_document_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='KYC Document Type'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KYC Submitted At'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KYC Verified At'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Maximum Allowed Capital (Demo/Real)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=64, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_risk_limit_breach',
            field=models.BooleanField(default=True, verbose_name='Notify on Risk Limit Breach'),
        ),
    ]
