# Generated by Django 5.2.8 on 2025-11-28 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_created_at_customuser_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Is Account Locked'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('institutional', 'Institutional'), ('developer', 'Developer')], default='individual', max_length=20, verbose_name='User Type'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username_display',
            field=models.CharField(blank=True, help_text='A public username for the user.', max_length=150, null=True, unique=True, verbose_name='Display Username'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Email Verified'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Last Name')),
                ('display_name', models.CharField(blank=True, max_length=128, verbose_name='Display Name')),
                ('phone_number', models.CharField(blank=True, max_length=32, verbose_name='Phone Number')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Two-Factor Authentication Enabled')),
                ('api_access_enabled', models.BooleanField(default=False, verbose_name='API Access Enabled')),
                ('max_api_requests_per_minute', models.IntegerField(default=1000, verbose_name='Max API Requests Per Minute')),
                ('preferred_base_currency', models.CharField(default='IRT', max_length=16, verbose_name='Preferred Base Currency')),
                ('default_leverage', models.IntegerField(default=1, verbose_name='Default Leverage')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=20, verbose_name='Risk Level')),
                ('max_active_trades', models.IntegerField(default=5, verbose_name='Max Active Trades')),
                ('notify_on_trade', models.BooleanField(default=True, verbose_name='Notify on Trade Execution')),
                ('notify_on_balance_change', models.BooleanField(default=True, verbose_name='Notify on Balance Change')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
