# Generated by Django 5.2.8 on 2025-11-30 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('bots', '0002_initial'),
        ('exchanges', '0001_initial'),
        ('instruments', '0001_initial'),
        ('risk', '0001_initial'),
        ('signals', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8, verbose_name='Side')),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop'), ('STOP_LIMIT', 'Stop Limit'), ('TAKE_PROFIT', 'Take Profit'), ('TAKE_PROFIT_LIMIT', 'Take Profit Limit'), ('TRAILING_STOP', 'Trailing Stop')], max_length=17, verbose_name='Order Type')),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=32, verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True, verbose_name='Price')),
                ('stop_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True, verbose_name='Stop Price')),
                ('time_in_force', models.CharField(choices=[('GTC', 'Good Till Canceled'), ('IOC', 'Immediate or Cancel'), ('FOK', 'Fill or Kill'), ('GTX', 'Good Till Crossing'), ('GTD', 'Good Till Date')], default='GTC', max_length=16, verbose_name='Time in Force')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NEW', max_length=32, verbose_name='Status')),
                ('client_order_id', models.CharField(max_length=64, unique=True, verbose_name='Client Order ID')),
                ('exchange_order_id', models.CharField(blank=True, max_length=64, verbose_name='Exchange Order ID')),
                ('commission_paid', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Commission Paid')),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True, verbose_name='Stop Loss Price')),
                ('take_profit_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True, verbose_name='Take Profit Price')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='agents.agent', verbose_name='Agent (MAS)')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bots.bot', verbose_name='Bot')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='exchanges.exchangeaccount', verbose_name='Exchange Account')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='instruments.instrument', verbose_name='Instrument')),
                ('risk_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='risk.riskprofile', verbose_name='Risk Profile')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='signals.signal', verbose_name='Signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(max_length=32, verbose_name='Old Status')),
                ('new_status', models.CharField(max_length=32, verbose_name='New Status')),
                ('message', models.TextField(blank=True, verbose_name='Log Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details (JSON)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='trading.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Log',
                'verbose_name_plural': 'Order Logs',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_id', models.CharField(max_length=64, verbose_name='Trade ID')),
                ('price', models.DecimalField(decimal_places=16, max_digits=32, verbose_name='Price')),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=32, verbose_name='Quantity')),
                ('fee', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Fee')),
                ('fee_asset', models.CharField(blank=True, max_length=32, verbose_name='Fee Asset')),
                ('executed_at', models.DateTimeField(verbose_name='Executed At')),
                ('source_event', models.CharField(blank=True, max_length=64, verbose_name='Source Event')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='agents.agent', verbose_name='Agent (MAS)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.order', verbose_name='Order')),
                ('strategy_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategyversion', verbose_name='Strategy Version')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=8, verbose_name='Side')),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=32, verbose_name='Quantity')),
                ('avg_entry_price', models.DecimalField(decimal_places=16, max_digits=32, verbose_name='Average Entry Price')),
                ('leverage', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Leverage')),
                ('liquidation_price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True, verbose_name='Liquidation Price')),
                ('margin_used', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Margin Used')),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Unrealized P&L')),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Realized P&L')),
                ('opened_at', models.DateTimeField(verbose_name='Opened At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16, verbose_name='Status')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='agents.agent', verbose_name='Agent (MAS)')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='bots.bot', verbose_name='Bot')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='exchanges.exchangeaccount', verbose_name='Exchange Account')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='instruments.instrument', verbose_name='Instrument')),
                ('strategy_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategyversion', verbose_name='Strategy Version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('entry_trades', models.ManyToManyField(related_name='entry_positions', to='trading.trade', verbose_name='Entry Trades')),
                ('exit_trades', models.ManyToManyField(blank=True, related_name='exit_positions', to='trading.trade', verbose_name='Exit Trades')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_order_id'], name='trading_ord_client__9d3b04_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['exchange_order_id'], name='trading_ord_exchang_b68492_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='trading_ord_user_id_ca9b05_idx'),
        ),
        migrations.AddIndex(
            model_name='orderlog',
            index=models.Index(fields=['order', '-created_at'], name='trading_ord_order_i_dea29c_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['executed_at', 'order'], name='trading_tra_execute_7a9051_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together={('order', 'trade_id')},
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user', 'status', '-opened_at'], name='trading_pos_user_id_9c045c_idx'),
        ),
    ]
