# Generated by Django 5.2.8 on 2025-11-26 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_symbol', models.CharField(help_text='e.g., BTCUSDT', max_length=64)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop'), ('STOP_LIMIT', 'Stop Limit')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=32)),
                ('price', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True)),
                ('time_in_force', models.CharField(default='GTC', max_length=16)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], default='NEW', max_length=32)),
                ('client_order_id', models.CharField(max_length=64, unique=True)),
                ('exchange_order_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='exchanges.exchangeaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_symbol', models.CharField(help_text='e.g., BTCUSDT', max_length=64)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=32)),
                ('avg_entry_price', models.DecimalField(decimal_places=16, max_digits=32)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='exchanges.exchangeaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(blank=True, max_length=64)),
                ('price', models.DecimalField(decimal_places=16, max_digits=32)),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=32)),
                ('fee', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('fee_asset', models.CharField(blank=True, max_length=32)),
                ('executed_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.order')),
            ],
        ),
    ]
