# Generated by Django 5.2.8 on 2025-11-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_user_balance_user_created_at_user_is_trader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
