# Generated by Django 5.2.8 on 2025-11-29 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_PASSWORD_CHANGE', 'User Password Change'), ('USER_PROFILE_UPDATE', 'User Profile Update'), ('BOT_CREATE', 'Bot Create'), ('BOT_UPDATE', 'Bot Update'), ('BOT_DELETE', 'Bot Delete'), ('RISK_PROFILE_UPDATE', 'Risk Profile Update'), ('ORDER_PLACE', 'Order Place'), ('ORDER_CANCEL', 'Order Cancel'), ('API_KEY_CREATE', 'API Key Create'), ('API_KEY_DELETE', 'API Key Delete'), ('SECURITY_EVENT', 'Security Event')], max_length=64, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details (JSON)')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Channel Name')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Channel Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('TELEGRAM', 'Telegram'), ('PUSH', 'Push Notification'), ('WEBHOOK', 'Webhook')], max_length=16, verbose_name='Delivery Method')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Is Encrypted')),
                ('rate_limit_per_minute', models.IntegerField(default=100, verbose_name='Rate Limit Per Minute')),
                ('credentials_encrypted', models.JSONField(blank=True, default=dict, help_text="e.g., {'api_key': '...', 'bot_token': '...'}", verbose_name='Encrypted Credentials (JSON)')),
                ('config', models.JSONField(blank=True, default=dict, help_text="e.g., {'smtp_host': '...'}", verbose_name='Configuration (JSON)')),
            ],
            options={
                'verbose_name': 'Notification Channel',
                'verbose_name_plural': 'Notification Channels',
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('SYSTEM', 'System'), ('AGENT', 'Agent'), ('BOT', 'Bot'), ('RISK', 'Risk'), ('TRADING', 'Trading'), ('BACKTEST', 'Backtest'), ('SECURITY', 'Security')], max_length=16, verbose_name='Event Category')),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical'), (5, 'Emergency')], verbose_name='Severity')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('source_component', models.CharField(max_length=128, verbose_name='Source Component')),
                ('source_instance_id', models.CharField(blank=True, max_length=128, verbose_name='Source Instance ID')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details (JSON)')),
            ],
            options={
                'verbose_name': 'System Event',
                'verbose_name_plural': 'System Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=16, verbose_name='Log Level')),
                ('source', models.CharField(help_text="e.g., 'RiskAgent', 'ExecutionAgent', 'Django.Views'", max_length=128, verbose_name='Source')),
                ('message', models.TextField(verbose_name='Log Message')),
                ('context', models.JSONField(blank=True, default=dict, help_text="e.g., {'order_id': 123, 'error_code': 'E101'}", verbose_name='Context (JSON)')),
                ('trace_id', models.CharField(blank=True, max_length=128, verbose_name='Trace ID')),
                ('request_id', models.CharField(blank=True, max_length=128, verbose_name='Request ID')),
                ('correlation_id', models.CharField(blank=True, max_length=128, verbose_name='Correlation ID')),
                ('severity_score', models.FloatField(default=0.0, verbose_name='Severity Score (0.0 - 5.0)')),
                ('resource_usage_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Resource Usage Snapshot (JSON)')),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(help_text="e.g., 'ORDER_FILLED'", max_length=64, verbose_name='Alert Type')),
                ('is_enabled', models.BooleanField(default=True, help_text='If user wants to receive this alert type on this channel.', verbose_name='Is Enabled')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Is Muted')),
                ('mute_until', models.DateTimeField(blank=True, null=True, verbose_name='Mute Until')),
                ('delivery_schedule', models.JSONField(blank=True, default=dict, help_text="e.g., {'days': ['Mon', 'Wed', 'Fri'], 'time_range': ['09:00', '17:00']}", verbose_name='Delivery Schedule (JSON)')),
            ],
            options={
                'verbose_name': 'User Notification Preference',
                'verbose_name_plural': 'User Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=32, verbose_name='Alert Type')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, verbose_name='Priority')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=16, verbose_name='Status')),
                ('payload', models.JSONField(blank=True, default=dict, help_text="e.g., {'order_id': 123, 'price': 45000}", verbose_name='Payload (JSON)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Is Acknowledged')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged By')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bots.bot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
