# Generated by Django 5.2.8 on 2025-11-30 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('bots', '0002_initial'),
        ('logging_app', '0001_initial'),
        ('signals', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trading.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='alert',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trading.position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='alert',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logging_app_alerts', to='signals.signal', verbose_name='Signal'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='alert',
            name='channels_sent',
            field=models.ManyToManyField(blank=True, related_name='sent_alerts', to='logging_app.notificationchannel', verbose_name='Channels Sent'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['category', '-created_at'], name='logging_app_categor_06c25c_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['severity', '-created_at'], name='logging_app_severit_cfc475_idx'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='agents.agent', verbose_name='Agent Context (MAS)'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='bots.bot', verbose_name='Bot Context'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='User Context'),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='logging_app.notificationchannel', verbose_name='Notification Channel'),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='logging_app_user_id_85dbec_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='logging_app_action_179fed_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['correlation_id'], name='logging_app_correla_63ee21_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='logging_app_status_1ea55b_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_acknowledged', '-created_at'], name='logging_app_is_ackn_b2e004_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['correlation_id'], name='logging_app_correla_5223c7_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['level', '-created_at'], name='logging_app_level_d98557_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['trace_id'], name='logging_app_trace_i_2275c6_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user', '-created_at'], name='logging_app_user_id_54543d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationpreference',
            unique_together={('user', 'alert_type', 'channel')},
        ),
    ]
