# Generated by Django 5.2.8 on 2025-11-29 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('exchanges', '0001_initial'),
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Strategy Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('ENTRY', 'Entry Signal'), ('EXIT', 'Exit Signal'), ('FULL', 'Full Strategy'), ('RISK', 'Risk Model'), ('ML', 'ML Model'), ('AI', 'AI Model'), ('PRICE_ACTION', 'Price Action Strategy'), ('SMART_MONEY', 'Smart Money Concept Strategy')], default='FULL', max_length=16, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public (for marketplace)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=20, verbose_name='Risk Level')),
                ('source_code_encrypted', models.TextField(blank=True, verbose_name='Encrypted Source Code')),
                ('code_language', models.CharField(default='Python', max_length=32, verbose_name='Code Language')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
            },
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32, verbose_name='Version')),
                ('parameters_schema', models.JSONField(default=dict, verbose_name='Parameters Schema (JSON)')),
                ('indicator_configs', models.JSONField(default=list, verbose_name='Indicator Configs (JSON)')),
                ('price_action_configs', models.JSONField(default=list, verbose_name='Price Action Configs (JSON)')),
                ('smart_money_configs', models.JSONField(default=list, verbose_name='Smart Money Configs (JSON)')),
                ('ai_metrics_configs', models.JSONField(default=list, verbose_name='AI Metrics Configs (JSON)')),
                ('source_code_ref', models.CharField(blank=True, max_length=256, verbose_name='Source Code Reference (Path, Git Ref, ...)')),
                ('model_artifact_ref', models.CharField(blank=True, max_length=256, verbose_name='Model Artifact Reference (Path, MLflow, ...)')),
                ('is_approved_for_live', models.BooleanField(default=False, verbose_name='Is Approved for Live Trading')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='strategies.strategy', verbose_name='Strategy')),
            ],
            options={
                'verbose_name': 'Strategy Version',
                'verbose_name_plural': 'Strategy Versions',
                'unique_together': {('strategy', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16, verbose_name='Status')),
                ('timeframe', models.CharField(max_length=16, verbose_name='Timeframe')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='End Datetime')),
                ('initial_capital', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Initial Capital')),
                ('position_size_mode', models.CharField(default='fixed', help_text='fixed / percent / risk_pct', max_length=16, verbose_name='Position Size Mode')),
                ('position_size_value', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Position Size Value')),
                ('parameters', models.JSONField(default=dict, verbose_name='Run Parameters (JSON)')),
                ('runtime_config', models.JSONField(default=dict, verbose_name='Runtime Config (JSON)')),
                ('result_summary', models.JSONField(default=dict, verbose_name='Result Summary (JSON)')),
                ('result_ref', models.CharField(blank=True, help_text='Reference to detailed results in MongoDB', max_length=256, verbose_name='Detailed Result Reference (MongoDB)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('exchange_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchanges.exchangeaccount', verbose_name='Exchange Account (for data source)')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument', verbose_name='Instrument')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategies.strategyversion', verbose_name='Strategy Version')),
            ],
            options={
                'verbose_name': 'Backtest Run',
                'verbose_name_plural': 'Backtest Runs',
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=128, verbose_name='Order ID')),
                ('trade_id', models.CharField(max_length=128, verbose_name='Trade ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4, verbose_name='Side')),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=32, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Price')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='P&L')),
                ('entry_signal_confidence', models.FloatField(blank=True, null=True, verbose_name='Entry Signal Confidence')),
                ('exit_reason', models.CharField(blank=True, max_length=64, verbose_name='Exit Reason')),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_results', to='strategies.backtestrun', verbose_name='Backtest Run')),
            ],
            options={
                'verbose_name': 'Backtest Result Detail',
                'verbose_name_plural': 'Backtest Result Details',
                'indexes': [models.Index(fields=['backtest_run', 'timestamp'], name='strategies__backtes_7d294e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StrategyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(default=1.0, verbose_name='Weight (for ensemble)')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority (for execution order)')),
                ('parameters_override', models.JSONField(default=dict, verbose_name='Parameters Override (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active on this Bot')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_assignments', to='bots.bot', verbose_name='Bot')),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_assignments', to='strategies.strategyversion', verbose_name='Strategy Version')),
            ],
            options={
                'verbose_name': 'Strategy Assignment',
                'verbose_name_plural': 'Strategy Assignments',
                'unique_together': {('bot', 'strategy_version')},
            },
        ),
    ]
