# Generated by Django 5.2.8 on 2025-11-30 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Strategy Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('ENTRY', 'Entry Signal'), ('EXIT', 'Exit Signal'), ('FULL', 'Full Strategy'), ('RISK', 'Risk Model'), ('ML', 'ML Model'), ('AI', 'AI Model'), ('PRICE_ACTION', 'Price Action Strategy'), ('SMART_MONEY', 'Smart Money Concept Strategy')], default='FULL', max_length=16, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public (for marketplace)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=20, verbose_name='Risk Level')),
                ('source_code_encrypted', models.TextField(blank=True, verbose_name='Encrypted Source Code')),
                ('code_language', models.CharField(default='Python', max_length=32, verbose_name='Code Language')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
            },
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32, verbose_name='Version')),
                ('parameters_schema', models.JSONField(default=dict, verbose_name='Parameters Schema (JSON)')),
                ('indicator_configs', models.JSONField(default=list, verbose_name='Indicator Configs (JSON)')),
                ('price_action_configs', models.JSONField(default=list, verbose_name='Price Action Configs (JSON)')),
                ('smart_money_configs', models.JSONField(default=list, verbose_name='Smart Money Configs (JSON)')),
                ('ai_metrics_configs', models.JSONField(default=list, verbose_name='AI Metrics Configs (JSON)')),
                ('source_code_ref', models.CharField(blank=True, max_length=256, verbose_name='Source Code Reference (Path, Git Ref, ...)')),
                ('model_artifact_ref', models.CharField(blank=True, max_length=256, verbose_name='Model Artifact Reference (Path, MLflow, ...)')),
                ('is_approved_for_live', models.BooleanField(default=False, verbose_name='Is Approved for Live Trading')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='strategies.strategy', verbose_name='Strategy')),
            ],
            options={
                'verbose_name': 'Strategy Version',
                'verbose_name_plural': 'Strategy Versions',
                'unique_together': {('strategy', 'version')},
            },
        ),
        migrations.CreateModel(
            name='StrategyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(default=1.0, verbose_name='Weight (for ensemble)')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority (for execution order)')),
                ('parameters_override', models.JSONField(default=dict, verbose_name='Parameters Override (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active on this Bot')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_assignments', to='bots.bot', verbose_name='Bot')),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_assignments', to='strategies.strategyversion', verbose_name='Strategy Version')),
            ],
            options={
                'verbose_name': 'Strategy Assignment',
                'verbose_name_plural': 'Strategy Assignments',
                'unique_together': {('bot', 'strategy_version')},
            },
        ),
    ]
