# Generated by Django 5.2.8 on 2025-11-26 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ENTRY', 'Entry Signal'), ('EXIT', 'Exit Signal'), ('FULL', 'Full Strategy'), ('RISK', 'Risk Model'), ('ML', 'ML Model')], default='FULL', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('parameters_schema', models.JSONField(default=dict)),
                ('indicator_configs', models.JSONField(default=list)),
                ('price_action_configs', models.JSONField(default=list)),
                ('smart_money_configs', models.JSONField(default=list)),
                ('ai_metrics_configs', models.JSONField(default=list)),
                ('code_ref', models.CharField(blank=True, max_length=256)),
                ('is_approved_for_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='strategies.strategy')),
            ],
            options={
                'unique_together': {('strategy', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('instrument_symbol', models.CharField(help_text='e.g., BTCUSDT', max_length=64)),
                ('timeframe', models.CharField(help_text='e.g., 1h, 4h, 1d', max_length=16)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('initial_capital', models.DecimalField(decimal_places=8, default=0, max_digits=32)),
                ('position_size_mode', models.CharField(default='fixed', help_text='fixed / percent', max_length=16)),
                ('position_size_value', models.DecimalField(decimal_places=8, default=0, max_digits=32)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters for this specific run')),
                ('runtime_config', models.JSONField(default=dict, help_text='commission, slippage, etc.')),
                ('result_summary', models.JSONField(default=dict, help_text='PnL, drawdown, win_rate, ...')),
                ('result_ref', models.CharField(blank=True, help_text='Reference to detailed results in MongoDB', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL)),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategies.strategyversion')),
            ],
        ),
    ]
