# Generated by Django 5.2.8 on 2025-11-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtestrun',
            name='exchange_account',
        ),
        migrations.RemoveField(
            model_name='backtestrun',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='backtestrun',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='backtestrun',
            name='strategy_version',
        ),
        migrations.DeleteModel(
            name='BacktestResult',
        ),
        migrations.DeleteModel(
            name='BacktestRun',
        ),
    ]
