# Generated by Django 5.2.8 on 2025-11-29 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Metric Name')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('data_type', models.CharField(default='float', max_length=16, verbose_name='Data Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'AI Metric',
                'verbose_name_plural': 'AI Metrics',
            },
        ),
        migrations.CreateModel(
            name='IndicatorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Indicator Group',
                'verbose_name_plural': 'Indicator Groups',
            },
        ),
        migrations.CreateModel(
            name='InstrumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Instrument Category',
                'verbose_name_plural': 'Instrument Categories',
            },
        ),
        migrations.CreateModel(
            name='InstrumentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Instrument Group',
                'verbose_name_plural': 'Instrument Groups',
            },
        ),
        migrations.CreateModel(
            name='PriceActionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Pattern Name')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Price Action Pattern',
                'verbose_name_plural': 'Price Action Patterns',
            },
        ),
        migrations.CreateModel(
            name='SmartMoneyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='SMC Name')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Smart Money Concept',
                'verbose_name_plural': 'Smart Money Concepts',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='Display Name')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_builtin', models.BooleanField(default=True, verbose_name='Is Built-in')),
                ('version', models.CharField(default='1.0.0', max_length=32, verbose_name='Version')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='instruments.indicatorgroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
            },
        ),
        migrations.CreateModel(
            name='IndicatorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parameters', models.JSONField(verbose_name='Parameters (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.indicator', verbose_name='Indicator')),
            ],
            options={
                'verbose_name': 'Indicator Template',
                'verbose_name_plural': 'Indicator Templates',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=64, verbose_name='Symbol')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Full Name')),
                ('base_asset', models.CharField(blank=True, max_length=32, verbose_name='Base Asset')),
                ('quote_asset', models.CharField(blank=True, max_length=32, verbose_name='Quote Asset')),
                ('tick_size', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Tick Size')),
                ('lot_size', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Lot Size')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata (JSON)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='instruments.instrumentcategory', verbose_name='Category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='instruments.instrumentgroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
            },
        ),
        migrations.CreateModel(
            name='IndicatorParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='Parameter Name')),
                ('display_name', models.CharField(max_length=128, verbose_name='Display Name')),
                ('data_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('str', 'String'), ('choice', 'Choice List')], max_length=16, verbose_name='Data Type')),
                ('default_value', models.TextField(blank=True, verbose_name='Default Value')),
                ('min_value', models.TextField(blank=True, verbose_name='Minimum Value')),
                ('max_value', models.TextField(blank=True, verbose_name='Maximum Value')),
                ('choices', models.TextField(blank=True, help_text="Used if data_type is 'choice'", verbose_name='Choices (comma-separated)')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='instruments.indicator', verbose_name='Indicator')),
            ],
            options={
                'verbose_name': 'Indicator Parameter',
                'verbose_name_plural': 'Indicator Parameters',
                'unique_together': {('indicator', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InstrumentExchangeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_symbol', models.CharField(max_length=64, verbose_name='Exchange Symbol')),
                ('tick_size', models.DecimalField(decimal_places=16, max_digits=32, verbose_name='Exchange Tick Size')),
                ('lot_size', models.DecimalField(decimal_places=16, max_digits=32, verbose_name='Exchange Lot Size')),
                ('min_notional', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Min Notional')),
                ('max_notional', models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True, verbose_name='Max Notional')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active on Exchange')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_mappings', to='exchanges.exchange', verbose_name='Exchange')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_mappings', to='instruments.instrument', verbose_name='Instrument')),
            ],
            options={
                'verbose_name': 'Instrument-Exchange Map',
                'verbose_name_plural': 'Instrument-Exchange Maps',
                'unique_together': {('exchange', 'exchange_symbol')},
            },
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(fields=('symbol',), name='unique_instrument_symbol'),
        ),
    ]
