# Generated by Django 5.2.8 on 2025-11-26 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='instruments.indicatorgroup')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('data_type', models.CharField(max_length=16)),
                ('default_value', models.CharField(blank=True, max_length=64)),
                ('min_value', models.CharField(blank=True, max_length=64)),
                ('max_value', models.CharField(blank=True, max_length=64)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='instruments.indicator')),
            ],
            options={
                'unique_together': {('indicator', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('base_asset', models.CharField(blank=True, max_length=32)),
                ('quote_asset', models.CharField(blank=True, max_length=32)),
                ('tick_size', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('lot_size', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='instruments.instrumentgroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('symbol',), name='unique_instrument_symbol')],
            },
        ),
    ]
