# Generated by Django 5.2.8 on 2025-11-29 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        ('instruments', '0001_initial'),
        ('strategies', '0002_remove_backtestrun_exchange_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16, verbose_name='Status')),
                ('timeframe', models.CharField(max_length=16, verbose_name='Timeframe')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='End Datetime')),
                ('initial_capital', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Initial Capital')),
                ('position_size_mode', models.CharField(default='fixed', help_text='fixed / percent / risk_pct', max_length=16, verbose_name='Position Size Mode')),
                ('position_size_value', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Position Size Value')),
                ('parameters', models.JSONField(default=dict, verbose_name='Run Parameters (JSON)')),
                ('runtime_config', models.JSONField(default=dict, verbose_name='Runtime Config (JSON)')),
                ('result_summary', models.JSONField(default=dict, verbose_name='Result Summary (JSON)')),
                ('result_ref', models.CharField(blank=True, help_text='Reference to detailed results in MongoDB', max_length=256, verbose_name='Detailed Result Reference (MongoDB)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('exchange_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchanges.exchangeaccount', verbose_name='Exchange Account (for data source)')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument', verbose_name='Instrument')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='strategies.strategyversion', verbose_name='Strategy Version')),
            ],
            options={
                'verbose_name': 'Backtest Run',
                'verbose_name_plural': 'Backtest Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=128, verbose_name='Order ID')),
                ('trade_id', models.CharField(max_length=128, verbose_name='Trade ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4, verbose_name='Side')),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=32, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Price')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='P&L')),
                ('entry_signal_confidence', models.FloatField(blank=True, null=True, verbose_name='Entry Signal Confidence')),
                ('exit_reason', models.CharField(blank=True, max_length=64, verbose_name='Exit Reason')),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_results', to='backtesting.backtestrun', verbose_name='Backtest Run')),
            ],
            options={
                'verbose_name': 'Backtest Result Detail',
                'verbose_name_plural': 'Backtest Result Details',
            },
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['owner', '-created_at'], name='backtesting_owner_i_33e3de_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['status'], name='backtesting_status_9ab73b_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['backtest_run', 'timestamp'], name='backtesting_backtes_7a863a_idx'),
        ),
    ]
