# Generated by Django 5.2.8 on 2025-11-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtesting', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='strategy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='strategies.strategyversion', verbose_name='Strategy Version'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='backtest_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_results', to='backtesting.backtestrun', verbose_name='Backtest Run'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['owner', '-created_at'], name='backtesting_owner_i_33e3de_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['status'], name='backtesting_status_9ab73b_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['backtest_run', 'timestamp'], name='backtesting_backtes_7a863a_idx'),
        ),
    ]
