# Generated by Django 5.2.8 on 2025-11-28 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(choices=[('CRYPTO', 'Crypto Exchange'), ('STOCK', 'Stock Broker'), ('FOREX', 'Forex Broker')], max_length=16)),
                ('base_url', models.URLField()),
                ('ws_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AggregatedPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=16)),
                ('total_equity', models.DecimalField(decimal_places=8, default=0, max_digits=32)),
                ('total_unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32)),
                ('total_realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=128)),
                ('api_key_encrypted', models.TextField()),
                ('api_secret_encrypted', models.TextField()),
                ('extra_credentials', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='exchanges.exchange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exchange', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures'), ('MARGIN', 'Margin'), ('OTHER', 'Other')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('is_default', models.BooleanField(default=False)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='exchanges.exchangeaccount')),
            ],
        ),
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=32)),
                ('total_balance', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('available_balance', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('in_order_balance', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='exchanges.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'asset_symbol')},
            },
        ),
    ]
