# Generated by Django 5.2.8 on 2025-11-30 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Exchange Name')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Exchange Code')),
                ('type', models.CharField(choices=[('CRYPTO', 'Crypto Exchange'), ('STOCK', 'Stock Broker'), ('FOREX', 'Forex Broker'), ('FUTURES', 'Futures Exchange'), ('OPTIONS', 'Options Exchange')], max_length=16, verbose_name='Exchange Type')),
                ('base_url', models.URLField(verbose_name='Base API URL')),
                ('ws_url', models.URLField(blank=True, verbose_name='WebSocket URL')),
                ('api_docs_url', models.URLField(blank=True, verbose_name='API Documentation URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_sandbox', models.BooleanField(default=False, verbose_name='Is Sandbox/Testnet')),
                ('rate_limit_per_second', models.IntegerField(default=10, verbose_name='Rate Limit Per Second')),
                ('fees_structure', models.JSONField(blank=True, default=dict, verbose_name='Fees Structure (JSON)')),
                ('limits', models.JSONField(blank=True, default=dict, verbose_name='Limits (JSON)')),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
            },
        ),
        migrations.CreateModel(
            name='AggregatedPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(default='USD', max_length=16, verbose_name='Base Currency')),
                ('total_equity', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Total Equity')),
                ('total_unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Total Unrealized PnL')),
                ('total_realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Total Realized PnL')),
                ('total_pnl_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Total PnL Percentage')),
                ('total_commission_paid', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Total Commission Paid')),
                ('total_funding_fees', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Total Funding Fees')),
                ('last_valuation_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Valuation At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_portfolio', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Aggregated Portfolio',
                'verbose_name_plural': 'Aggregated Portfolios',
            },
        ),
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=128, verbose_name='Account Label')),
                ('api_key_encrypted', models.TextField(verbose_name='Encrypted API Key')),
                ('api_secret_encrypted', models.TextField(verbose_name='Encrypted API Secret')),
                ('encrypted_key_iv', models.CharField(blank=True, max_length=255, verbose_name='Encryption IV/Nonce')),
                ('extra_credentials', models.JSONField(blank=True, default=dict, verbose_name='Extra Credentials (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_paper_trading', models.BooleanField(default=False, verbose_name='Is Paper Trading Account')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync At')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Account Created IP')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='exchanges.exchange', verbose_name='Exchange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_accounts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Exchange Account',
                'verbose_name_plural': 'Exchange Accounts',
                'unique_together': {('user', 'exchange', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet_type', models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures'), ('MARGIN', 'Margin'), ('ISOLATED_MARGIN', 'Isolated Margin'), ('FUNDING', 'Funding'), ('OTHER', 'Other')], max_length=16, verbose_name='Wallet Type')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Wallet')),
                ('is_margin_enabled', models.BooleanField(default=False, verbose_name='Is Margin Enabled')),
                ('leverage', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Leverage')),
                ('borrowed_amount', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Borrowed Amount')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='exchanges.exchangeaccount', verbose_name='Exchange Account')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='AggregatedAssetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_symbol', models.CharField(max_length=32, verbose_name='Asset Symbol')),
                ('total_quantity', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Total Quantity')),
                ('total_value_in_base_currency', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Total Value in Base Currency')),
                ('per_exchange_breakdown', models.JSONField(default=dict, verbose_name='Per Exchange Breakdown (JSON)')),
                ('aggregated_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_positions', to='exchanges.aggregatedportfolio', verbose_name='Aggregated Portfolio')),
            ],
            options={
                'verbose_name': 'Aggregated Asset Position',
                'verbose_name_plural': 'Aggregated Asset Positions',
                'unique_together': {('aggregated_portfolio', 'asset_symbol')},
            },
        ),
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_symbol', models.CharField(max_length=32, verbose_name='Asset Symbol')),
                ('total_balance', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Total Balance')),
                ('available_balance', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Available Balance')),
                ('in_order_balance', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Balance in Orders')),
                ('frozen_balance', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Frozen Balance')),
                ('borrowed_balance', models.DecimalField(decimal_places=16, default=0, max_digits=32, verbose_name='Borrowed Balance')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='exchanges.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Balance',
                'verbose_name_plural': 'Wallet Balances',
                'unique_together': {('wallet', 'asset_symbol')},
            },
        ),
    ]
