# Generated by Django 5.2.8 on 2025-11-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key_encrypted', models.TextField(verbose_name='Encrypted API Key')),
                ('api_secret_encrypted', models.TextField(verbose_name='Encrypted API Secret')),
                ('encrypted_key_iv', models.CharField(blank=True, max_length=255, verbose_name='Encryption IV/Nonce')),
                ('extra_credentials_encrypted', models.JSONField(blank=True, default=dict, verbose_name='Extra Encrypted Credentials (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('exchange_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_credential', to='exchanges.exchangeaccount', verbose_name='Exchange Account')),
            ],
            options={
                'verbose_name': 'API Credential',
                'verbose_name_plural': 'API Credentials',
            },
        ),
        migrations.CreateModel(
            name='ExchangeConnectorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_base_url', models.URLField(verbose_name='API Base URL')),
                ('ws_base_url', models.URLField(blank=True, verbose_name='WebSocket Base URL')),
                ('sandbox_api_base_url', models.URLField(blank=True, verbose_name='Sandbox API Base URL')),
                ('sandbox_ws_base_url', models.URLField(blank=True, verbose_name='Sandbox WebSocket Base URL')),
                ('rate_limit_per_minute', models.IntegerField(default=1200, verbose_name='Rate Limit Per Minute')),
                ('is_sandbox_mode_default', models.BooleanField(default=False, verbose_name='Is Sandbox Mode Default')),
                ('default_credentials_encrypted', models.JSONField(blank=True, default=dict, verbose_name='Default Encrypted Credentials (JSON)')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Connector Configuration (JSON)')),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connector_config', to='exchanges.exchange', verbose_name='Exchange')),
            ],
            options={
                'verbose_name': 'Exchange Connector Config',
                'verbose_name_plural': 'Exchange Connector Configs',
            },
        ),
        migrations.CreateModel(
            name='RateLimitState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint_path', models.CharField(max_length=256)),
                ('window_start_at', models.DateTimeField()),
                ('requests_count', models.IntegerField(default=0)),
                ('is_rate_limited', models.BooleanField(default=False)),
                ('retry_after', models.DateTimeField(blank=True, null=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='exchanges.exchangeaccount')),
            ],
            options={
                'verbose_name': 'Rate Limit State',
                'verbose_name_plural': 'Rate Limit States',
            },
        ),
        migrations.CreateModel(
            name='ConnectorHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_healthy', models.BooleanField(verbose_name='Is Healthy')),
                ('latency_ms', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Latency (ms)')),
                ('last_check_at', models.DateTimeField(verbose_name='Last Check At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='exchanges.exchangeaccount', verbose_name='Exchange Account')),
            ],
            options={
                'verbose_name': 'Connector Health Check',
                'verbose_name_plural': 'Connector Health Checks',
                'ordering': ['-last_check_at'],
                'indexes': [models.Index(fields=['exchange_account', '-last_check_at'], name='connectors__exchang_258527_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=16, verbose_name='Log Level')),
                ('action', models.CharField(max_length=128, verbose_name='Action')),
                ('endpoint', models.CharField(max_length=256, verbose_name='Endpoint')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Request Payload (JSON)')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Response Payload (JSON)')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Status Code')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('correlation_id', models.CharField(blank=True, max_length=128, verbose_name='Correlation ID')),
                ('trace_id', models.CharField(blank=True, max_length=128, verbose_name='Trace ID')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_logs', to='exchanges.exchangeaccount', verbose_name='Exchange Account')),
            ],
            options={
                'verbose_name': 'Connector Log',
                'verbose_name_plural': 'Connector Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['exchange_account', '-created_at'], name='connectors__exchang_265967_idx'), models.Index(fields=['correlation_id'], name='connectors__correla_b60093_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=128, verbose_name='Session ID')),
                ('session_type', models.CharField(choices=[('WEBSOCKET', 'WebSocket'), ('REST', 'REST Session'), ('STREAM', 'Data Stream')], max_length=16, verbose_name='Session Type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error')], max_length=16)),
                ('connected_at', models.DateTimeField()),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exchanges.exchangeaccount')),
            ],
            options={
                'verbose_name': 'Connector Session',
                'verbose_name_plural': 'Connector Sessions',
                'unique_together': {('exchange_account', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeAPIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint_path', models.CharField(max_length=256, verbose_name='Endpoint Path')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('is_sandbox_supported', models.BooleanField(default=True)),
                ('rate_limit_weight', models.IntegerField(default=1, verbose_name='Weight for Rate Limiter')),
                ('description', models.TextField(blank=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='exchanges.exchange')),
            ],
            options={
                'verbose_name': 'Exchange API Endpoint',
                'verbose_name_plural': 'Exchange API Endpoints',
                'unique_together': {('exchange', 'endpoint_path', 'method')},
            },
        ),
    ]
