# Generated by Django 5.2.8 on 2025-11-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Agent Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_paused_by_system', models.BooleanField(default=False, verbose_name='Is Paused by System')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity At')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='1.0.0', max_length=32, verbose_name='Config Version')),
                ('params', models.JSONField(default=dict, verbose_name='Parameters (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('validation_result', models.JSONField(blank=True, default=dict, verbose_name='Validation Result (JSON)')),
            ],
            options={
                'verbose_name': 'Agent Config',
                'verbose_name_plural': 'Agent Configs',
            },
        ),
        migrations.CreateModel(
            name='AgentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_id', models.CharField(max_length=128, verbose_name='Instance ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed')], default='STOPPED', max_length=16, verbose_name='Status')),
                ('host', models.CharField(blank=True, max_length=256, verbose_name='Host')),
                ('process_id', models.IntegerField(blank=True, null=True, verbose_name='Process ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='Stopped At')),
            ],
            options={
                'verbose_name': 'Agent Instance',
                'verbose_name_plural': 'Agent Instances',
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=16, verbose_name='Log Level')),
                ('message', models.TextField(verbose_name='Log Message')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra Data (JSON)')),
                ('trace_id', models.CharField(blank=True, max_length=128, verbose_name='Trace ID')),
                ('resource_usage_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Resource Usage Snapshot (JSON)')),
                ('agent_instance_id', models.CharField(blank=True, max_length=128, verbose_name='Agent Instance ID')),
            ],
            options={
                'verbose_name': 'Agent Log',
                'verbose_name_plural': 'Agent Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(max_length=64, verbose_name='Message Type')),
                ('topic', models.CharField(blank=True, max_length=128, verbose_name='Topic')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload (JSON)')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, verbose_name='Priority')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Is Encrypted')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('processed', models.BooleanField(default=False, verbose_name='Is Processed')),
            ],
            options={
                'verbose_name': 'Agent Message',
                'verbose_name_plural': 'Agent Messages',
            },
        ),
        migrations.CreateModel(
            name='AgentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField(verbose_name='Period Start')),
                ('period_end', models.DateTimeField(verbose_name='Period End')),
                ('cpu_usage_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Avg CPU Usage (%)')),
                ('memory_usage_avg_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Avg Memory Usage (MB)')),
                ('disk_usage_avg_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Avg Disk Usage (MB)')),
                ('network_io_avg_kb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Avg Network I/O (KB/s)')),
                ('messages_sent', models.IntegerField(default=0, verbose_name='Messages Sent')),
                ('messages_received', models.IntegerField(default=0, verbose_name='Messages Received')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Errors Count')),
                ('avg_processing_time_ms', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Avg Processing Time (ms)')),
            ],
            options={
                'verbose_name': 'Agent Metric',
                'verbose_name_plural': 'Agent Metrics',
            },
        ),
        migrations.CreateModel(
            name='AgentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('ERROR', 'Error'), ('STOPPED', 'Stopped')], default='IDLE', max_length=32, verbose_name='State')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Heartbeat At')),
                ('last_error', models.TextField(blank=True, verbose_name='Last Error')),
                ('metrics', models.JSONField(default=dict, verbose_name='Metrics (JSON)')),
                ('agent_version', models.CharField(blank=True, max_length=32, verbose_name='Agent Version')),
                ('process_id', models.IntegerField(blank=True, null=True, verbose_name='Process ID')),
            ],
            options={
                'verbose_name': 'Agent Status',
                'verbose_name_plural': 'Agent Statuses',
            },
        ),
        migrations.CreateModel(
            name='AgentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Agent Type Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('capabilities', models.JSONField(default=dict, verbose_name='Capabilities (JSON)')),
                ('is_system_managed', models.BooleanField(default=False, verbose_name='Is System Managed')),
                ('allowed_parameters', models.JSONField(default=dict, verbose_name='Allowed Parameters Schema (JSON)')),
            ],
            options={
                'verbose_name': 'Agent Type',
                'verbose_name_plural': 'Agent Types',
            },
        ),
    ]
