# Generated by Django 5.2.8 on 2025-11-29 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='assigned_strategy_versions',
            field=models.ManyToManyField(blank=True, related_name='assigned_agents', to='strategies.strategyversion', verbose_name='Assigned Strategy Versions'),
        ),
        migrations.AddField(
            model_name='agent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='agent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agents', to=settings.AUTH_USER_MODEL, verbose_name='Owner (User)'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='agentinstance',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='agentlog',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='agentlog',
            name='user_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Context'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='agents.agent', verbose_name='Receiver Agent'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='agents.agent', verbose_name='Sender Agent'),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='agentstatus',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='receiver_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_agent_messages', to='agents.agenttype', verbose_name='Receiver Type (Cached)'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='sender_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_agent_messages', to='agents.agenttype', verbose_name='Sender Type (Cached)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='agents.agenttype', verbose_name='Agent Type'),
        ),
        migrations.AlterUniqueTogether(
            name='agentinstance',
            unique_together={('agent', 'instance_id')},
        ),
        migrations.AddIndex(
            model_name='agentlog',
            index=models.Index(fields=['agent', '-created_at'], name='agents_agen_agent_i_d48305_idx'),
        ),
        migrations.AddIndex(
            model_name='agentlog',
            index=models.Index(fields=['level'], name='agents_agen_level_e148ef_idx'),
        ),
        migrations.AddIndex(
            model_name='agentlog',
            index=models.Index(fields=['trace_id'], name='agents_agen_trace_i_0418b1_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmetric',
            index=models.Index(fields=['agent', '-period_end'], name='agents_agen_agent_i_fa6e54_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['topic', '-created_at'], name='agents_agen_topic_45e99a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['correlation_id'], name='agents_agen_correla_3b3843_idx'),
        ),
    ]
