# Generated by Django 5.2.8 on 2025-11-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agentstatus',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='agentstatus',
            name='state',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('ERROR', 'Error'), ('STOPPED', 'Stopped')], default='IDLE', max_length=32),
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='agents.agent')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=16)),
                ('message', models.TextField()),
                ('extra_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agents.agent')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent', 'timestamp'], name='agents_agen_agent_i_41257d_idx'), models.Index(fields=['level'], name='agents_agen_level_e148ef_idx')],
            },
        ),
    ]
