# Generated by Django 5.2.8 on 2025-11-29 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Data Source Name')),
                ('type', models.CharField(choices=[('REST', 'REST API'), ('WEBSOCKET', 'WebSocket'), ('FILE', 'File Import'), ('FTP', 'FTP'), ('DATABASE', 'Database')], max_length=32, verbose_name='Source Type')),
                ('base_url', models.URLField(blank=True, verbose_name='Base URL')),
                ('rate_limit_per_minute', models.IntegerField(default=100, verbose_name='Rate Limit Per Minute')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration (JSON)')),
                ('credentials_encrypted', models.JSONField(blank=True, default=dict, verbose_name='Encrypted Credentials (JSON)')),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
            },
        ),
        migrations.CreateModel(
            name='MarketDataConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeframe', models.CharField(max_length=16, verbose_name='Timeframe')),
                ('storage_backend', models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('MONGODB', 'MongoDB'), ('TIMESCALE', 'TimescaleDB')], default='MONGODB', max_length=16, verbose_name='Storage Backend')),
                ('data_format', models.CharField(choices=[('OHLCV', 'OHLCV'), ('TICK', 'Tick Data'), ('ORDER_BOOK', 'Order Book'), ('CUSTOM', 'Custom Format')], default='OHLCV', max_length=16, verbose_name='Data Format')),
                ('collection_name', models.CharField(help_text='e.g., binance_spot_btcusdt_1m', max_length=128, verbose_name='Collection/ Table Name')),
                ('is_realtime', models.BooleanField(default=False, verbose_name='Is Real-time')),
                ('is_historical', models.BooleanField(default=True, verbose_name='Is Historical')),
                ('preprocessing_pipeline', models.JSONField(blank=True, default=dict, verbose_name='Preprocessing Pipeline (JSON)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync At')),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Successful Sync At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_data_configs', to='market_data.datasource', verbose_name='Data Source')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data_configs', to='instruments.instrument', verbose_name='Instrument')),
            ],
            options={
                'verbose_name': 'Market Data Config',
                'verbose_name_plural': 'Market Data Configs',
                'unique_together': {('instrument', 'timeframe', 'data_source')},
            },
        ),
        migrations.CreateModel(
            name='MarketDataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16, verbose_name='Status')),
                ('start_time', models.DateTimeField(verbose_name='Sync Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Sync End Time')),
                ('records_synced', models.PositiveIntegerField(default=0, verbose_name='Number of Records Synced')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('sync_details', models.JSONField(blank=True, default=dict, verbose_name='Sync Details (JSON)')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='market_data.marketdataconfig', verbose_name='Market Data Config')),
            ],
            options={
                'verbose_name': 'Market Data Sync Log',
                'verbose_name_plural': 'Market Data Sync Logs',
            },
        ),
        migrations.CreateModel(
            name='MarketDataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeframe', models.CharField(max_length=16, verbose_name='Timeframe')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Open Price')),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='High Price')),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Low Price')),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Close Price')),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='Volume')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='instruments.instrument', verbose_name='Instrument')),
            ],
            options={
                'verbose_name': 'Market Data Snapshot',
                'verbose_name_plural': 'Market Data Snapshots',
                'indexes': [models.Index(fields=['instrument', 'timeframe', 'timestamp'], name='market_data_instrum_658215_idx')],
                'unique_together': {('instrument', 'timeframe', 'timestamp')},
            },
        ),
    ]
