# Generated by Django 5.2.8 on 2025-11-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('REST_API', 'REST API'), ('WEBSOCKET', 'WebSocket'), ('FILE', 'File Import'), ('DATABASE', 'Database')], max_length=16, verbose_name='Type')),
                ('base_url', models.URLField(blank=True, verbose_name='Base URL')),
                ('ws_url', models.URLField(blank=True, verbose_name='WebSocket URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('rate_limit_per_minute', models.IntegerField(default=1200, verbose_name='Rate Limit Per Minute')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration (JSON)')),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
            },
        ),
        migrations.CreateModel(
            name='MarketDataConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeframe', models.CharField(max_length=16, verbose_name='Timeframe')),
                ('data_type', models.CharField(choices=[('TICK', 'Tick Data'), ('OHLCV', 'OHLCV'), ('ORDER_BOOK', 'Order Book'), ('TRADES', 'Trades'), ('INDEX', 'Index'), ('FUNDING_RATE', 'Funding Rate')], max_length=32, verbose_name='Data Type')),
                ('is_realtime', models.BooleanField(default=False, verbose_name='Is Real-time')),
                ('is_historical', models.BooleanField(default=True, verbose_name='Is Historical')),
                ('storage_backend', models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('MONGODB', 'MongoDB'), ('TIMESCALE', 'TimescaleDB')], default='POSTGRES', max_length=32, verbose_name='Storage Backend')),
                ('collection_or_table_name', models.CharField(help_text='e.g., binance_spot_btcusdt_1m_ticks', max_length=128, verbose_name='Collection/ Table Name')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBSCRIBED', 'Subscribed'), ('UNSUBSCRIBED', 'Unsubscribed'), ('ERROR', 'Error')], default='PENDING', max_length=16, verbose_name='Status')),
                ('api_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectors.apicredential', verbose_name='API Credential (if required)')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configs', to='market_data.datasource', verbose_name='Data Source')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data_configs', to='instruments.instrument', verbose_name='Instrument')),
            ],
            options={
                'verbose_name': 'Market Data Config',
                'verbose_name_plural': 'Market Data Configs',
                'unique_together': {('instrument', 'data_source', 'timeframe', 'data_type')},
            },
        ),
        migrations.CreateModel(
            name='MarketDataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(verbose_name='Sync Start Time')),
                ('end_time', models.DateTimeField(verbose_name='Sync End Time')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], max_length=16, verbose_name='Status')),
                ('records_synced', models.IntegerField(default=0, verbose_name='Records Synced')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details (JSON)')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='market_data.marketdataconfig', verbose_name='Market Data Config')),
            ],
            options={
                'verbose_name': 'Market Data Sync Log',
                'verbose_name_plural': 'Market Data Sync Logs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MarketDataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Open Price')),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='High Price')),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Low Price')),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Close Price')),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='Volume')),
                ('best_bid', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Best Bid')),
                ('best_ask', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Best Ask')),
                ('bid_size', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, verbose_name='Bid Size')),
                ('ask_size', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, verbose_name='Ask Size')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='Additional Data (JSON)')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='market_data.marketdataconfig', verbose_name='Market Data Config')),
            ],
            options={
                'verbose_name': 'Market Data Snapshot',
                'verbose_name_plural': 'Market Data Snapshots',
                'indexes': [models.Index(fields=['config', '-timestamp'], name='market_data_config__51ca93_idx'), models.Index(fields=['timestamp'], name='market_data_timesta_3f5fde_idx')],
            },
        ),
    ]
