# Generated by Django 5.2.8 on 2025-11-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0002_instrumentgroup_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketDataConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeframe', models.CharField(max_length=16)),
                ('collection_name', models.CharField(help_text='e.g., binance_spot_btcusdt_1m', max_length=128)),
                ('is_realtime', models.BooleanField(default=False, help_text='If true, this config is for real-time data.')),
                ('is_historical', models.BooleanField(default=True, help_text='If true, this config is for historical data.')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_data_configs', to='market_data.datasource')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data_configs', to='instruments.instrument')),
            ],
            options={
                'unique_together': {('instrument', 'timeframe', 'data_source')},
            },
        ),
    ]
