# Generated by Django 5.2.8 on 2025-11-26 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('bot_type', models.CharField(choices=[('BUY_ONLY', 'Buy Only'), ('SELL_ONLY', 'Sell Only'), ('LONG_SHORT', 'Long & Short'), ('GRID', 'Grid Bot'), ('DCA', 'Dollar Cost Averaging')], default='LONG_SHORT', max_length=16)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='INACTIVE', max_length=16)),
                ('mode', models.CharField(choices=[('LIVE', 'Live Trading'), ('PAPER', 'Paper Trading')], default='PAPER', max_length=16)),
                ('max_concurrent_trades', models.IntegerField(default=1)),
                ('desired_profit_target_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_allowed_loss_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('schedule_config', models.JSONField(blank=True, default=dict, help_text="e.g., {'start_time': '09:00', 'end_time': '17:00', 'days': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='exchanges.exchangeaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotStrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text="Weight of this strategy in the bot's decisions")),
                ('is_primary', models.BooleanField(default=False, help_text='Mark if this is the primary strategy')),
                ('parameters_override', models.JSONField(blank=True, default=dict, help_text='Override default strategy parameters for this bot')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_configs', to='bots.bot')),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_configs', to='strategies.strategyversion')),
            ],
            options={
                'unique_together': {('bot', 'strategy_version')},
            },
        ),
    ]
