# Generated by Django 5.2.8 on 2025-11-28 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        ('instruments', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('bot_type', models.CharField(choices=[('BUY_ONLY', 'Buy Only'), ('SELL_ONLY', 'Sell Only'), ('LONG_SHORT', 'Long & Short'), ('GRID', 'Grid Bot'), ('DCA', 'Dollar Cost Averaging')], default='LONG_SHORT', max_length=16)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='INACTIVE', max_length=16)),
                ('mode', models.CharField(choices=[('LIVE', 'Live Trading'), ('PAPER', 'Paper Trading')], default='PAPER', max_length=16)),
                ('control_type', models.CharField(choices=[('MANUAL', 'Manual Control by User'), ('AUTOMATIC', 'Automatic Control by System')], default='MANUAL', help_text='How the bot is started/stopped.', max_length=16)),
                ('max_concurrent_trades', models.IntegerField(default=1, help_text='Maximum number of open trades/positions.')),
                ('desired_profit_target_percent', models.DecimalField(blank=True, decimal_places=4, help_text='Target profit in percentage (e.g., 2.50 for 2.5%).', max_digits=8, null=True)),
                ('max_allowed_loss_percent', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum allowed loss in percentage.', max_digits=8, null=True)),
                ('paper_trading_balance', models.DecimalField(decimal_places=8, default=10000, help_text='Starting balance for paper trading mode.', max_digits=32)),
                ('schedule_config', models.JSONField(blank=True, default=dict, help_text="e.g., {'start_time': '09:00', 'end_time': '17:00', 'days': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']}")),
                ('last_error_log', models.TextField(blank=True, help_text='Stores the last error message for debugging.')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Last time the bot sent a heartbeat signal.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='exchanges.exchangeaccount')),
                ('instrument', models.ForeignKey(blank=True, help_text='The specific trading instrument for this bot.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='instruments.instrument')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BotStrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text="Weight of this strategy in the bot's final decision.")),
                ('is_primary', models.BooleanField(default=False, help_text='Mark if this is the primary strategy for the bot.')),
                ('parameters_override', models.JSONField(blank=True, default=dict, help_text='Override default strategy parameters for this specific bot.')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_configs', to='bots.bot')),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_configs', to='strategies.strategyversion')),
            ],
            options={
                'unique_together': {('bot', 'strategy_version')},
            },
        ),
    ]
