# Generated by Django 5.2.8 on 2025-11-30 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('STARTED', 'Started'), ('STOPPED', 'Stopped'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info'), ('SIGNAL_RECEIVED', 'Signal Received'), ('ORDER_PLACED', 'Order Placed'), ('ORDER_FILLED', 'Order Filled'), ('POSITION_OPENED', 'Position Opened'), ('POSITION_CLOSED', 'Position Closed')], max_length=32, verbose_name='Event Type')),
                ('message', models.TextField(verbose_name='Log Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details (JSON)')),
            ],
            options={
                'verbose_name': 'Bot Log',
                'verbose_name_plural': 'Bot Logs',
            },
        ),
        migrations.CreateModel(
            name='BotPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField(verbose_name='Period Start')),
                ('period_end', models.DateTimeField(verbose_name='Period End')),
                ('total_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Total P&L')),
                ('total_pnl_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Total P&L (%)')),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Realized P&L')),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=32, verbose_name='Unrealized P&L')),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Max Drawdown (%)')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Sharpe Ratio')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Total Trades')),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Win Rate (%)')),
                ('avg_trade_duration', models.DurationField(blank=True, null=True, verbose_name='Average Trade Duration')),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Profit Factor')),
            ],
            options={
                'verbose_name': 'Bot Performance Snapshot',
                'verbose_name_plural': 'Bot Performance Snapshots',
            },
        ),
        migrations.CreateModel(
            name='BotStrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(default=1.0, help_text="Weight of this strategy in the bot's final decision.", verbose_name='Weight')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark if this is the primary strategy for the bot.', verbose_name='Is Primary')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('parameters_override', models.JSONField(blank=True, default=dict, help_text='Override default strategy parameters for this specific bot.', verbose_name='Parameters Override (JSON)')),
                ('last_execution_result', models.JSONField(blank=True, default=dict, verbose_name='Last Execution Result (JSON)')),
            ],
            options={
                'verbose_name': 'Bot Strategy Config',
                'verbose_name_plural': 'Bot Strategy Configs',
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Bot Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('bot_type', models.CharField(choices=[('BUY_ONLY', 'Buy Only'), ('SELL_ONLY', 'Sell Only'), ('LONG_SHORT', 'Long & Short'), ('GRID', 'Grid Bot'), ('DCA', 'Dollar Cost Averaging'), ('ARBITRAGE', 'Arbitrage'), ('MEAN_REVERSION', 'Mean Reversion'), ('TREND_FOLLOWING', 'Trend Following')], default='LONG_SHORT', max_length=16, verbose_name='Bot Type')),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='INACTIVE', max_length=16, verbose_name='Status')),
                ('mode', models.CharField(choices=[('LIVE', 'Live Trading'), ('PAPER', 'Paper Trading')], default='PAPER', max_length=16, verbose_name='Trading Mode')),
                ('control_type', models.CharField(choices=[('MANUAL', 'Manual Control by User'), ('AUTOMATIC', 'Automatic Control by System')], default='MANUAL', help_text='How the bot is started/stopped.', max_length=16, verbose_name='Control Type')),
                ('max_concurrent_trades', models.IntegerField(default=1, help_text='Maximum number of open trades/positions.', verbose_name='Max Concurrent Trades')),
                ('max_position_size', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='Max Position Size')),
                ('max_total_capital', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='Max Total Capital to Use')),
                ('leverage', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Leverage')),
                ('desired_profit_target_percent', models.DecimalField(blank=True, decimal_places=4, help_text='Target profit in percentage (e.g., 2.50 for 2.5%).', max_digits=8, null=True, verbose_name='Desired Profit Target (%)')),
                ('max_allowed_loss_percent', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum allowed loss in percentage.', max_digits=8, null=True, verbose_name='Max Allowed Loss (%)')),
                ('trailing_stop_config', models.JSONField(blank=True, default=dict, verbose_name='Trailing Stop Config (JSON)')),
                ('schedule_config', models.JSONField(blank=True, default=dict, help_text="e.g., {'start_time': '09:00', 'end_time': '17:00', 'days': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']}", verbose_name='Schedule Config (JSON)')),
                ('paper_trading_balance', models.DecimalField(decimal_places=8, default=10000, help_text='Starting balance for paper trading mode.', max_digits=32, verbose_name='Paper Trading Balance')),
                ('last_error_log', models.TextField(blank=True, help_text='Stores the last error message for debugging.', verbose_name='Last Error Log')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Last time the bot sent a heartbeat signal.', null=True, verbose_name='Last Heartbeat At')),
                ('is_paused_by_system', models.BooleanField(default=False, verbose_name='Is Paused by System')),
                ('performance_metrics', models.JSONField(blank=True, default=dict, verbose_name='Performance Metrics (JSON)')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='exchanges.exchangeaccount', verbose_name='Exchange Account')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='instruments.instrument', verbose_name='Trading Instrument')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
            },
        ),
    ]
