# Generated by Django 5.2.8 on 2025-11-26 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='control_type',
            field=models.CharField(choices=[('MANUAL', 'Manual Control by User'), ('AUTOMATIC', 'Automatic Control by System')], default='MANUAL', help_text='How the bot is started/stopped.', max_length=16),
        ),
        migrations.AddField(
            model_name='bot',
            name='instrument',
            field=models.ForeignKey(blank=True, help_text='The specific trading instrument for this bot.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='instruments.instrument'),
        ),
        migrations.AddField(
            model_name='bot',
            name='last_error_log',
            field=models.TextField(blank=True, help_text='Stores the last error message for debugging.'),
        ),
        migrations.AddField(
            model_name='bot',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='Last time the bot sent a heartbeat signal.', null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='paper_trading_balance',
            field=models.DecimalField(decimal_places=8, default=10000, help_text='Starting balance for paper trading mode.', max_digits=32),
        ),
        migrations.AlterField(
            model_name='bot',
            name='desired_profit_target_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Target profit in percentage (e.g., 2.50 for 2.5%).', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='max_allowed_loss_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Maximum allowed loss in percentage.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='max_concurrent_trades',
            field=models.IntegerField(default=1, help_text='Maximum number of open trades/positions.'),
        ),
        migrations.AlterField(
            model_name='botstrategyconfig',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark if this is the primary strategy for the bot.'),
        ),
        migrations.AlterField(
            model_name='botstrategyconfig',
            name='parameters_override',
            field=models.JSONField(blank=True, default=dict, help_text='Override default strategy parameters for this specific bot.'),
        ),
        migrations.AlterField(
            model_name='botstrategyconfig',
            name='weight',
            field=models.FloatField(default=1.0, help_text="Weight of this strategy in the bot's final decision."),
        ),
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together={('owner', 'name')},
        ),
    ]
