# Generated by Django 5.2.8 on 2025-11-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('risk', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='risk_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='risk.riskprofile', verbose_name='Risk Profile'),
        ),
        migrations.AddField(
            model_name='botlog',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bots.bot', verbose_name='Bot'),
        ),
        migrations.AddField(
            model_name='botperformancesnapshot',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='bots.bot', verbose_name='Bot'),
        ),
        migrations.AddField(
            model_name='botstrategyconfig',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_configs', to='bots.bot', verbose_name='Bot'),
        ),
        migrations.AddField(
            model_name='botstrategyconfig',
            name='strategy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_configs', to='strategies.strategyversion', verbose_name='Strategy Version'),
        ),
        migrations.AlterUniqueTogether(
            name='bot',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['bot', '-created_at'], name='bots_botlog_bot_id_15737e_idx'),
        ),
        migrations.AddIndex(
            model_name='botperformancesnapshot',
            index=models.Index(fields=['bot', '-period_end'], name='bots_botper_bot_id_fb796c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='botstrategyconfig',
            unique_together={('bot', 'strategy_version')},
        ),
    ]
