# Generated by Django 5.2.8 on 2025-11-28 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('instruments', '0001_initial'),
        ('logging_app', '0001_initial'),
        ('strategies', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('CLOSE_LONG', 'Close Long'), ('CLOSE_SHORT', 'Close Short')], max_length=16)),
                ('signal_type', models.CharField(choices=[('ENTRY', 'Entry Signal'), ('EXIT', 'Exit Signal'), ('TAKE_PROFIT', 'Take Profit'), ('STOP_LOSS', 'Stop Loss'), ('SCALE_IN', 'Scale In'), ('SCALE_OUT', 'Scale Out')], default='ENTRY', max_length=16)),
                ('price', models.DecimalField(blank=True, decimal_places=16, help_text='Suggested price for limit orders.', max_digits=32, null=True)),
                ('quantity', models.DecimalField(decimal_places=16, help_text='Suggested quantity.', max_digits=32)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence of the signal from 0.0 to 1.0')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Additional data like indicators, AI scores, etc.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved by Risk'), ('REJECTED', 'Rejected by Risk'), ('EXECUTED', 'Executed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Signal is invalid after this time.', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Time when signal was processed by risk agent.', null=True)),
                ('bot', models.ForeignKey(blank=True, help_text='The bot this signal is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='bots.bot')),
                ('final_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_signal', to='trading.order')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='instruments.instrument')),
                ('related_log_entry', models.ForeignKey(blank=True, help_text="Links to a system log entry if this signal's processing caused an event.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_signals', to='logging_app.systemlog')),
                ('strategy_version', models.ForeignKey(blank=True, help_text='The strategy version that generated this signal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='strategies.strategyversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
