# Generated by Django 5.2.8 on 2025-11-29 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('bots', '0002_initial'),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('HIGH_CONFIDENCE', 'High Confidence Signal'), ('RISK_REJECTION', 'Risk Rejection'), ('EXECUTION_ERROR', 'Execution Error'), ('MANUAL_OVERRIDE', 'Manual Override')], max_length=32, verbose_name='Alert Type')),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], verbose_name='Severity')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details (JSON)')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Is Acknowledged')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
            ],
            options={
                'verbose_name': 'Signal Alert',
                'verbose_name_plural': 'Signal Alerts',
            },
        ),
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(max_length=17, verbose_name='Old Status')),
                ('new_status', models.CharField(max_length=17, verbose_name='New Status')),
                ('message', models.TextField(blank=True, verbose_name='Log Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details (JSON)')),
            ],
            options={
                'verbose_name': 'Signal Log',
                'verbose_name_plural': 'Signal Logs',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('CLOSE_LONG', 'Close Long'), ('CLOSE_SHORT', 'Close Short')], max_length=16, verbose_name='Direction')),
                ('signal_type', models.CharField(choices=[('ENTRY', 'Entry Signal'), ('EXIT', 'Exit Signal'), ('TAKE_PROFIT', 'Take Profit'), ('STOP_LOSS', 'Stop Loss'), ('SCALE_IN', 'Scale In'), ('SCALE_OUT', 'Scale Out'), ('LIQUIDATION', 'Liquidation Signal')], default='ENTRY', max_length=16, verbose_name='Signal Type')),
                ('price', models.DecimalField(blank=True, decimal_places=16, help_text='Suggested price for limit orders.', max_digits=32, null=True, verbose_name='Suggested Price')),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=32, verbose_name='Suggested Quantity')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence of the signal from 0.0 to 1.0', verbose_name='Confidence Score')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Additional data like indicators, AI scores, etc.', verbose_name='Payload (JSON)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT_TO_RISK', 'Sent to Risk Agent'), ('APPROVED', 'Approved by Risk'), ('REJECTED', 'Rejected by Risk'), ('SENT_TO_EXECUTION', 'Sent to Execution Agent'), ('EXECUTED', 'Executed'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='PENDING', max_length=17, verbose_name='Status')),
                ('priority', models.IntegerField(default=1, verbose_name='Priority (Higher = Processed First)')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Is Recurring')),
                ('sent_to_risk_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent to Risk At')),
                ('risk_approval_details', models.JSONField(blank=True, default=dict, verbose_name='Risk Approval Details (JSON)')),
                ('sent_to_execution_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent to Execution At')),
                ('generated_at', models.DateTimeField(verbose_name='Generated At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Signal is invalid after this time.', null=True, verbose_name='Expires At')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Time when signal was processed by risk agent.', null=True, verbose_name='Processed At')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
                ('agent', models.ForeignKey(blank=True, help_text='The agent that generated this signal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent', verbose_name='Agent (MAS)')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='bots.bot', verbose_name='Bot')),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='exchanges.exchangeaccount', verbose_name='Exchange Account')),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signals',
            },
        ),
    ]
