# Generated by Django 5.2.8 on 2025-11-29 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('instruments', '0001_initial'),
        ('signals', '0001_initial'),
        ('strategies', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='final_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_signal', to='trading.order', verbose_name='Final Order'),
        ),
        migrations.AddField(
            model_name='signal',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='instruments.instrument', verbose_name='Instrument'),
        ),
        migrations.AddField(
            model_name='signal',
            name='strategy_version',
            field=models.ForeignKey(blank=True, help_text='The strategy version that generated this signal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='strategies.strategyversion', verbose_name='Strategy Version'),
        ),
        migrations.AddField(
            model_name='signal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='signalalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged By'),
        ),
        migrations.AddField(
            model_name='signalalert',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_alerts', to='signals.signal', verbose_name='Signal'),
        ),
        migrations.AddField(
            model_name='signallog',
            name='changed_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent', verbose_name='Changed By Agent (MAS)'),
        ),
        migrations.AddField(
            model_name='signallog',
            name='changed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By User'),
        ),
        migrations.AddField(
            model_name='signallog',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='signals.signal', verbose_name='Signal'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['user', '-generated_at'], name='signals_sig_user_id_0014b7_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['status', '-generated_at'], name='signals_sig_status_54e52d_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['correlation_id'], name='signals_sig_correla_c44417_idx'),
        ),
        migrations.AddIndex(
            model_name='signalalert',
            index=models.Index(fields=['severity', '-created_at'], name='signals_sig_severit_fc3852_idx'),
        ),
        migrations.AddIndex(
            model_name='signalalert',
            index=models.Index(fields=['is_acknowledged', '-created_at'], name='signals_sig_is_ackn_56cda6_idx'),
        ),
        migrations.AddIndex(
            model_name='signallog',
            index=models.Index(fields=['signal', '-created_at'], name='signals_sig_signal__370f4e_idx'),
        ),
    ]
