# Generated by Django 5.2.8 on 2025-11-28 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Conservative, Aggressive, Custom Bot Risk', max_length=128)),
                ('max_daily_loss_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Max daily loss in % (e.g., 2.50 for 2.5%).', max_digits=5, null=True)),
                ('max_drawdown_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Max allowed drawdown in %.', max_digits=5, null=True)),
                ('max_position_size_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Max position size as % of total equity.', max_digits=5, null=True)),
                ('risk_per_trade_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Risk to take on a single trade in %.', max_digits=5, null=True)),
                ('use_trailing_stop', models.BooleanField(default=False, help_text='Enable trailing stop loss.')),
                ('trailing_stop_config', models.JSONField(blank=True, default=dict, help_text="e.g., {'activation_percent': 1.0, 'trail_percent': 0.5}")),
                ('bot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='bots.bot')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('LIMIT_BREACHED', 'Limit Breached'), ('STOP_LOSS_TRIGGERED', 'Stop Loss Triggered'), ('RULE_VIOLATION', 'Rule Violation'), ('WARNING', 'Warning')], max_length=32)),
                ('severity', models.IntegerField(default=1, help_text='Severity level from 1 to 5.')),
                ('message', models.TextField()),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='bots.bot')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='trading.order')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='trading.position')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='risk.riskprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(help_text="e.g., 'no_trading_weekends', 'max_open_positions'", max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text="Parameters for the rule, e.g., {'days': ['Sat', 'Sun']}")),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='risk.riskprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
