# Generated by Django 5.2.8 on 2025-11-29 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('bots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('value_at_risk', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='Value at Risk (VaR)')),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Max Drawdown (%)')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Sharpe Ratio')),
                ('volatility', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Volatility')),
                ('exposure', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='Total Exposure')),
                ('exposure_per_instrument', models.JSONField(blank=True, default=dict, verbose_name='Exposure per Instrument (JSON)')),
            ],
            options={
                'verbose_name': 'Risk Metric',
                'verbose_name_plural': 'Risk Metrics',
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Conservative, Aggressive, Custom Bot Risk', max_length=128, verbose_name='Profile Name')),
                ('risk_model_type', models.CharField(choices=[('CLASSIC', 'Classic Risk Model'), ('AI', 'AI Risk Model'), ('RAG', 'RAG-based Risk Model')], default='CLASSIC', max_length=16, verbose_name='Risk Model Type')),
                ('max_daily_loss_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Max daily loss in % (e.g., 2.50 for 2.5%).', max_digits=5, null=True, verbose_name='Max Daily Loss (%)')),
                ('max_drawdown_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Max allowed drawdown in %.', max_digits=5, null=True, verbose_name='Max Drawdown (%)')),
                ('max_position_size_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Max position size as % of total equity.', max_digits=5, null=True, verbose_name='Max Position Size (%)')),
                ('max_capital', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='Max Capital to Risk')),
                ('max_positions', models.IntegerField(blank=True, null=True, verbose_name='Max Open Positions')),
                ('max_exposure_per_instrument', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Max Exposure per Instrument (%)')),
                ('max_correlation_with_portfolio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Max Correlation with Portfolio (%)')),
                ('risk_per_trade_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Risk to take on a single trade in %.', max_digits=5, null=True, verbose_name='Risk per Trade (%)')),
                ('use_trailing_stop', models.BooleanField(default=False, help_text='Enable trailing stop loss.', verbose_name='Use Trailing Stop')),
                ('trailing_stop_config', models.JSONField(blank=True, default=dict, help_text="e.g., {'activation_percent': 1.0, 'trail_percent': 0.5}", verbose_name='Trailing Stop Config (JSON)')),
                ('use_ai_risk_model', models.BooleanField(default=False, verbose_name='Use AI Risk Model')),
            ],
            options={
                'verbose_name': 'Risk Profile',
                'verbose_name_plural': 'Risk Profiles',
            },
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Rule Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('rule_type', models.CharField(help_text="e.g., 'no_trading_weekends', 'max_open_positions'", max_length=64, verbose_name='Rule Type')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text="Parameters for the rule, e.g., {'days': ['Sat', 'Sun']}", verbose_name='Parameters (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority (Higher = Checked First)')),
                ('action', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny'), ('ADJUST', 'Adjust')], default='DENY', max_length=16, verbose_name='Action')),
            ],
            options={
                'verbose_name': 'Risk Rule',
                'verbose_name_plural': 'Risk Rules',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('THRESHOLD_BREACH', 'Threshold Breach'), ('RULE_VIOLATION', 'Rule Violation'), ('HIGH_RISK_SIGNAL', 'High Risk Signal'), ('SYSTEM_ANOMALY', 'System Anomaly')], max_length=32, verbose_name='Alert Type')),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical'), (5, 'Emergency')], verbose_name='Severity')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details (JSON)')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Is Acknowledged')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged By')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent', verbose_name='Agent (MAS)')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='bots.bot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Risk Alert',
                'verbose_name_plural': 'Risk Alerts',
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('LIMIT_BREACHED', 'Limit Breached'), ('STOP_LOSS_TRIGGERED', 'Stop Loss Triggered'), ('RULE_VIOLATION', 'Rule Violation'), ('WARNING', 'Warning'), ('LIQUIDATION', 'Position Liquidation'), ('RISK_MODEL_OVERRIDE', 'Risk Model Override')], max_length=32, verbose_name='Event Type')),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical'), (5, 'Emergency')], default=1, help_text='Severity level from 1 to 5.', verbose_name='Severity')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details (JSON)')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Is Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent', verbose_name='Agent (MAS)')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='bots.bot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Risk Event',
                'verbose_name_plural': 'Risk Events',
            },
        ),
    ]
