# Generated by Django 5.2.8 on 2025-11-30 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('bots', '0002_initial'),
        ('risk', '0001_initial'),
        ('signals', '0001_initial'),
        ('strategies', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='trading.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='trading.position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resolved By'),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.signal', verbose_name='Signal'),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='strategy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategyversion', verbose_name='Strategy Version'),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent', verbose_name='Agent (MAS)'),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='bots.bot', verbose_name='Bot'),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile_model', to='bots.bot', verbose_name='Bot Owner'),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to=settings.AUTH_USER_MODEL, verbose_name='User Owner'),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='risk_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_profiles', to='agents.agent', verbose_name='Responsible Agent (MAS)'),
        ),
        migrations.AddField(
            model_name='riskmetric',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='risk.riskprofile', verbose_name='Risk Profile'),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='risk.riskprofile', verbose_name='Risk Profile'),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='risk.riskprofile', verbose_name='Risk Profile'),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='agent_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent', verbose_name='Responsible Agent (MAS)'),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='risk.riskprofile', verbose_name='Risk Profile'),
        ),
        migrations.AddIndex(
            model_name='riskmetric',
            index=models.Index(fields=['profile', 'timestamp'], name='risk_riskme_profile_5bbbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['profile', '-created_at'], name='risk_riskev_profile_9d9d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['severity', '-created_at'], name='risk_riskev_severit_0772aa_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['severity', '-created_at'], name='risk_riskal_severit_4a5ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['is_acknowledged', '-created_at'], name='risk_riskal_is_ackn_18cb85_idx'),
        ),
    ]
