# Generated by Django 5.2.8 on 2025-12-01 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_initial'),
        ('risk', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Owner (User)'),
        ),
        migrations.AlterUniqueTogether(
            name='riskprofile',
            unique_together={('bot', 'name'), ('owner', 'name')},
        ),
    ]
